/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FooterWrapperItem, } from "./components/res/view/s-saqhan-app-footer/res/view/footer-wrapper/res/interface/common.interface";
import { SSaqhanCardAuthorItem, } from "./components/s-saqhan-second-page/res/view/s-saqhan-author-info/res/view/s-saqhan-card-author/interface/common.interface";
import { SSaqhanCardBannerItem, } from "./components/s-saqhan-second-page/res/view/s-saqhan-line-book/res/view/s-saqhan-card-banner/interface/common.interface";
import { SSaqhanEventCardItem, } from "./components/s-saqhan-component/res/view/s-saqhan-events-blog/res/interface/common.interface";
import { SSaqhanFirstSliderItem, } from "./components/s-saqhan-component/res/view/s-saqhan-first-slider/res/interface/common.interface";
import { logoUrl, SSaqhanHedearMenuItem, } from "./components/res/view/s-saqhan-header-app/res/interface/common.interface";
import { NewBlogItem, } from "./components/res/view/s-saqhan-new-blog/res/interface/commin.interface";
import { SSaqhanNewsCardItem, } from "./components/s-saqhan-item-news/res/view/s-saqhan-list-news/res/view/s-saqhan-news-card/interface/common.interface";
import { SSaqhanPopularCardItem, } from "./components/s-saqhan-component/res/view/s-saqhan-popular-news/res/interface/common.interface";
import { secondTitleBlockItem, } from "./components/s-saqhan-second-page/res/view/second-title-block/res/interface/common.interface";
export namespace Components {
    interface FooterFirstItem {
        "arr": any;
    }
    interface FooterWrapper {
        /**
          * массив 1 футера
         */
        "footer": FooterWrapperItem;
    }
    interface MenuItem {
        "arr": any;
    }
    interface SSaqhanAppFooter {
        /**
          * Инфо о компании в футере
         */
        "footerInfo": any;
        /**
          * массив меню для вывода
         */
        "footerItems": any;
    }
    interface SSaqhanAuthorInfo {
        "author": any;
    }
    interface SSaqhanBlogCard {
        /**
          * Массив с публикациями
         */
        "post": any;
    }
    interface SSaqhanBreadCard {
        "links": any;
    }
    interface SSaqhanBreadCrumbs {
        "links": any;
    }
    interface SSaqhanCardAuthor {
        "author": SSaqhanCardAuthorItem;
    }
    interface SSaqhanCardBanner {
        "bannerPost": SSaqhanCardBannerItem;
    }
    interface SSaqhanChatAddQuestion {
    }
    interface SSaqhanChatApp {
    }
    interface SSaqhanChatFiles {
    }
    interface SSaqhanChatFilesWrapper {
    }
    interface SSaqhanChatFormSearch {
    }
    interface SSaqhanChatFormSearchFiles {
    }
    interface SSaqhanChatMainUser {
        "mainUser": any;
    }
    interface SSaqhanChatMainUserCard {
        "main": any;
    }
    interface SSaqhanChatPersonal {
    }
    interface SSaqhanChatUser {
        "messages": any;
    }
    interface SSaqhanChatUserCard {
        "user": any;
    }
    interface SSaqhanChatUsers {
        "mainUser": any;
        "messages": any;
    }
    interface SSaqhanChatUsersWrapper {
        "mainUser": any;
        "messages": any;
    }
    interface SSaqhanChatWrapper {
        "mainUser": any;
        "messages": any;
        "showContent": string;
    }
    interface SSaqhanComponent {
    }
    interface SSaqhanEventCard {
        /**
          * Массив публикаций Ивентов
         */
        "event": any;
    }
    interface SSaqhanEventsBlog {
        /**
          * Массив с публикациями
         */
        "events": SSaqhanEventCardItem[];
    }
    interface SSaqhanFirstSlider {
        /**
          * массив новостей для вывода
         */
        "blogCarouselMock": SSaqhanFirstSliderItem[];
    }
    interface SSaqhanHeaderApp {
        /**
          * ссылка на изображение логотипа
         */
        "logoUrl": logoUrl;
        /**
          * массив меню для вывода
         */
        "menu": SSaqhanHedearMenuItem[];
        /**
          * текст вывода в кнопке подписаться
         */
        "subscribeText": string;
    }
    interface SSaqhanItemNews {
    }
    interface SSaqhanLentaNewsCard {
        /**
          * Массив с новостями для ленты
         */
        "lentaNews": any;
    }
    interface SSaqhanLineBook {
        "banner": any;
    }
    interface SSaqhanListNews {
        "news": any;
    }
    interface SSaqhanMainNewsCard {
        /**
          * Массив с новостями
         */
        "mainNews": any;
    }
    interface SSaqhanNewBlog {
        /**
          * Массив с публикациями
         */
        "blogPost": NewBlogItem[];
    }
    interface SSaqhanNewsCard {
        "news": SSaqhanNewsCardItem;
    }
    interface SSaqhanPopularCard {
        /**
          * Массив с популярными элементами
         */
        "post": any;
    }
    interface SSaqhanPopularNews {
        /**
          * Данные для баннера
         */
        "bannerPopular": any;
        /**
          * Массив публикаций
         */
        "popularNews": SSaqhanPopularCardItem[];
    }
    interface SSaqhanQuoteText {
        "quoteText": any;
    }
    interface SSaqhanSecondPage {
    }
    interface SSaqhanSubscBanner {
        /**
          * Массив данных для черного баннера
         */
        "subscribeBlockText": any;
        /**
          * текст вывода в кнопке подписаться
         */
        "subscribeText": string;
    }
    interface SecondTitleBlock {
        "secondTitle": secondTitleBlockItem;
    }
}
declare global {
    interface HTMLFooterFirstItemElement extends Components.FooterFirstItem, HTMLStencilElement {
    }
    var HTMLFooterFirstItemElement: {
        prototype: HTMLFooterFirstItemElement;
        new (): HTMLFooterFirstItemElement;
    };
    interface HTMLFooterWrapperElement extends Components.FooterWrapper, HTMLStencilElement {
    }
    var HTMLFooterWrapperElement: {
        prototype: HTMLFooterWrapperElement;
        new (): HTMLFooterWrapperElement;
    };
    interface HTMLMenuItemElement extends Components.MenuItem, HTMLStencilElement {
    }
    var HTMLMenuItemElement: {
        prototype: HTMLMenuItemElement;
        new (): HTMLMenuItemElement;
    };
    interface HTMLSSaqhanAppFooterElement extends Components.SSaqhanAppFooter, HTMLStencilElement {
    }
    var HTMLSSaqhanAppFooterElement: {
        prototype: HTMLSSaqhanAppFooterElement;
        new (): HTMLSSaqhanAppFooterElement;
    };
    interface HTMLSSaqhanAuthorInfoElement extends Components.SSaqhanAuthorInfo, HTMLStencilElement {
    }
    var HTMLSSaqhanAuthorInfoElement: {
        prototype: HTMLSSaqhanAuthorInfoElement;
        new (): HTMLSSaqhanAuthorInfoElement;
    };
    interface HTMLSSaqhanBlogCardElement extends Components.SSaqhanBlogCard, HTMLStencilElement {
    }
    var HTMLSSaqhanBlogCardElement: {
        prototype: HTMLSSaqhanBlogCardElement;
        new (): HTMLSSaqhanBlogCardElement;
    };
    interface HTMLSSaqhanBreadCardElement extends Components.SSaqhanBreadCard, HTMLStencilElement {
    }
    var HTMLSSaqhanBreadCardElement: {
        prototype: HTMLSSaqhanBreadCardElement;
        new (): HTMLSSaqhanBreadCardElement;
    };
    interface HTMLSSaqhanBreadCrumbsElement extends Components.SSaqhanBreadCrumbs, HTMLStencilElement {
    }
    var HTMLSSaqhanBreadCrumbsElement: {
        prototype: HTMLSSaqhanBreadCrumbsElement;
        new (): HTMLSSaqhanBreadCrumbsElement;
    };
    interface HTMLSSaqhanCardAuthorElement extends Components.SSaqhanCardAuthor, HTMLStencilElement {
    }
    var HTMLSSaqhanCardAuthorElement: {
        prototype: HTMLSSaqhanCardAuthorElement;
        new (): HTMLSSaqhanCardAuthorElement;
    };
    interface HTMLSSaqhanCardBannerElement extends Components.SSaqhanCardBanner, HTMLStencilElement {
    }
    var HTMLSSaqhanCardBannerElement: {
        prototype: HTMLSSaqhanCardBannerElement;
        new (): HTMLSSaqhanCardBannerElement;
    };
    interface HTMLSSaqhanChatAddQuestionElement extends Components.SSaqhanChatAddQuestion, HTMLStencilElement {
    }
    var HTMLSSaqhanChatAddQuestionElement: {
        prototype: HTMLSSaqhanChatAddQuestionElement;
        new (): HTMLSSaqhanChatAddQuestionElement;
    };
    interface HTMLSSaqhanChatAppElement extends Components.SSaqhanChatApp, HTMLStencilElement {
    }
    var HTMLSSaqhanChatAppElement: {
        prototype: HTMLSSaqhanChatAppElement;
        new (): HTMLSSaqhanChatAppElement;
    };
    interface HTMLSSaqhanChatFilesElement extends Components.SSaqhanChatFiles, HTMLStencilElement {
    }
    var HTMLSSaqhanChatFilesElement: {
        prototype: HTMLSSaqhanChatFilesElement;
        new (): HTMLSSaqhanChatFilesElement;
    };
    interface HTMLSSaqhanChatFilesWrapperElement extends Components.SSaqhanChatFilesWrapper, HTMLStencilElement {
    }
    var HTMLSSaqhanChatFilesWrapperElement: {
        prototype: HTMLSSaqhanChatFilesWrapperElement;
        new (): HTMLSSaqhanChatFilesWrapperElement;
    };
    interface HTMLSSaqhanChatFormSearchElement extends Components.SSaqhanChatFormSearch, HTMLStencilElement {
    }
    var HTMLSSaqhanChatFormSearchElement: {
        prototype: HTMLSSaqhanChatFormSearchElement;
        new (): HTMLSSaqhanChatFormSearchElement;
    };
    interface HTMLSSaqhanChatFormSearchFilesElement extends Components.SSaqhanChatFormSearchFiles, HTMLStencilElement {
    }
    var HTMLSSaqhanChatFormSearchFilesElement: {
        prototype: HTMLSSaqhanChatFormSearchFilesElement;
        new (): HTMLSSaqhanChatFormSearchFilesElement;
    };
    interface HTMLSSaqhanChatMainUserElement extends Components.SSaqhanChatMainUser, HTMLStencilElement {
    }
    var HTMLSSaqhanChatMainUserElement: {
        prototype: HTMLSSaqhanChatMainUserElement;
        new (): HTMLSSaqhanChatMainUserElement;
    };
    interface HTMLSSaqhanChatMainUserCardElement extends Components.SSaqhanChatMainUserCard, HTMLStencilElement {
    }
    var HTMLSSaqhanChatMainUserCardElement: {
        prototype: HTMLSSaqhanChatMainUserCardElement;
        new (): HTMLSSaqhanChatMainUserCardElement;
    };
    interface HTMLSSaqhanChatPersonalElement extends Components.SSaqhanChatPersonal, HTMLStencilElement {
    }
    var HTMLSSaqhanChatPersonalElement: {
        prototype: HTMLSSaqhanChatPersonalElement;
        new (): HTMLSSaqhanChatPersonalElement;
    };
    interface HTMLSSaqhanChatUserElement extends Components.SSaqhanChatUser, HTMLStencilElement {
    }
    var HTMLSSaqhanChatUserElement: {
        prototype: HTMLSSaqhanChatUserElement;
        new (): HTMLSSaqhanChatUserElement;
    };
    interface HTMLSSaqhanChatUserCardElement extends Components.SSaqhanChatUserCard, HTMLStencilElement {
    }
    var HTMLSSaqhanChatUserCardElement: {
        prototype: HTMLSSaqhanChatUserCardElement;
        new (): HTMLSSaqhanChatUserCardElement;
    };
    interface HTMLSSaqhanChatUsersElement extends Components.SSaqhanChatUsers, HTMLStencilElement {
    }
    var HTMLSSaqhanChatUsersElement: {
        prototype: HTMLSSaqhanChatUsersElement;
        new (): HTMLSSaqhanChatUsersElement;
    };
    interface HTMLSSaqhanChatUsersWrapperElement extends Components.SSaqhanChatUsersWrapper, HTMLStencilElement {
    }
    var HTMLSSaqhanChatUsersWrapperElement: {
        prototype: HTMLSSaqhanChatUsersWrapperElement;
        new (): HTMLSSaqhanChatUsersWrapperElement;
    };
    interface HTMLSSaqhanChatWrapperElement extends Components.SSaqhanChatWrapper, HTMLStencilElement {
    }
    var HTMLSSaqhanChatWrapperElement: {
        prototype: HTMLSSaqhanChatWrapperElement;
        new (): HTMLSSaqhanChatWrapperElement;
    };
    interface HTMLSSaqhanComponentElement extends Components.SSaqhanComponent, HTMLStencilElement {
    }
    var HTMLSSaqhanComponentElement: {
        prototype: HTMLSSaqhanComponentElement;
        new (): HTMLSSaqhanComponentElement;
    };
    interface HTMLSSaqhanEventCardElement extends Components.SSaqhanEventCard, HTMLStencilElement {
    }
    var HTMLSSaqhanEventCardElement: {
        prototype: HTMLSSaqhanEventCardElement;
        new (): HTMLSSaqhanEventCardElement;
    };
    interface HTMLSSaqhanEventsBlogElement extends Components.SSaqhanEventsBlog, HTMLStencilElement {
    }
    var HTMLSSaqhanEventsBlogElement: {
        prototype: HTMLSSaqhanEventsBlogElement;
        new (): HTMLSSaqhanEventsBlogElement;
    };
    interface HTMLSSaqhanFirstSliderElement extends Components.SSaqhanFirstSlider, HTMLStencilElement {
    }
    var HTMLSSaqhanFirstSliderElement: {
        prototype: HTMLSSaqhanFirstSliderElement;
        new (): HTMLSSaqhanFirstSliderElement;
    };
    interface HTMLSSaqhanHeaderAppElement extends Components.SSaqhanHeaderApp, HTMLStencilElement {
    }
    var HTMLSSaqhanHeaderAppElement: {
        prototype: HTMLSSaqhanHeaderAppElement;
        new (): HTMLSSaqhanHeaderAppElement;
    };
    interface HTMLSSaqhanItemNewsElement extends Components.SSaqhanItemNews, HTMLStencilElement {
    }
    var HTMLSSaqhanItemNewsElement: {
        prototype: HTMLSSaqhanItemNewsElement;
        new (): HTMLSSaqhanItemNewsElement;
    };
    interface HTMLSSaqhanLentaNewsCardElement extends Components.SSaqhanLentaNewsCard, HTMLStencilElement {
    }
    var HTMLSSaqhanLentaNewsCardElement: {
        prototype: HTMLSSaqhanLentaNewsCardElement;
        new (): HTMLSSaqhanLentaNewsCardElement;
    };
    interface HTMLSSaqhanLineBookElement extends Components.SSaqhanLineBook, HTMLStencilElement {
    }
    var HTMLSSaqhanLineBookElement: {
        prototype: HTMLSSaqhanLineBookElement;
        new (): HTMLSSaqhanLineBookElement;
    };
    interface HTMLSSaqhanListNewsElement extends Components.SSaqhanListNews, HTMLStencilElement {
    }
    var HTMLSSaqhanListNewsElement: {
        prototype: HTMLSSaqhanListNewsElement;
        new (): HTMLSSaqhanListNewsElement;
    };
    interface HTMLSSaqhanMainNewsCardElement extends Components.SSaqhanMainNewsCard, HTMLStencilElement {
    }
    var HTMLSSaqhanMainNewsCardElement: {
        prototype: HTMLSSaqhanMainNewsCardElement;
        new (): HTMLSSaqhanMainNewsCardElement;
    };
    interface HTMLSSaqhanNewBlogElement extends Components.SSaqhanNewBlog, HTMLStencilElement {
    }
    var HTMLSSaqhanNewBlogElement: {
        prototype: HTMLSSaqhanNewBlogElement;
        new (): HTMLSSaqhanNewBlogElement;
    };
    interface HTMLSSaqhanNewsCardElement extends Components.SSaqhanNewsCard, HTMLStencilElement {
    }
    var HTMLSSaqhanNewsCardElement: {
        prototype: HTMLSSaqhanNewsCardElement;
        new (): HTMLSSaqhanNewsCardElement;
    };
    interface HTMLSSaqhanPopularCardElement extends Components.SSaqhanPopularCard, HTMLStencilElement {
    }
    var HTMLSSaqhanPopularCardElement: {
        prototype: HTMLSSaqhanPopularCardElement;
        new (): HTMLSSaqhanPopularCardElement;
    };
    interface HTMLSSaqhanPopularNewsElement extends Components.SSaqhanPopularNews, HTMLStencilElement {
    }
    var HTMLSSaqhanPopularNewsElement: {
        prototype: HTMLSSaqhanPopularNewsElement;
        new (): HTMLSSaqhanPopularNewsElement;
    };
    interface HTMLSSaqhanQuoteTextElement extends Components.SSaqhanQuoteText, HTMLStencilElement {
    }
    var HTMLSSaqhanQuoteTextElement: {
        prototype: HTMLSSaqhanQuoteTextElement;
        new (): HTMLSSaqhanQuoteTextElement;
    };
    interface HTMLSSaqhanSecondPageElement extends Components.SSaqhanSecondPage, HTMLStencilElement {
    }
    var HTMLSSaqhanSecondPageElement: {
        prototype: HTMLSSaqhanSecondPageElement;
        new (): HTMLSSaqhanSecondPageElement;
    };
    interface HTMLSSaqhanSubscBannerElement extends Components.SSaqhanSubscBanner, HTMLStencilElement {
    }
    var HTMLSSaqhanSubscBannerElement: {
        prototype: HTMLSSaqhanSubscBannerElement;
        new (): HTMLSSaqhanSubscBannerElement;
    };
    interface HTMLSecondTitleBlockElement extends Components.SecondTitleBlock, HTMLStencilElement {
    }
    var HTMLSecondTitleBlockElement: {
        prototype: HTMLSecondTitleBlockElement;
        new (): HTMLSecondTitleBlockElement;
    };
    interface HTMLElementTagNameMap {
        "footer-first-item": HTMLFooterFirstItemElement;
        "footer-wrapper": HTMLFooterWrapperElement;
        "menu-item": HTMLMenuItemElement;
        "s-saqhan-app-footer": HTMLSSaqhanAppFooterElement;
        "s-saqhan-author-info": HTMLSSaqhanAuthorInfoElement;
        "s-saqhan-blog-card": HTMLSSaqhanBlogCardElement;
        "s-saqhan-bread-card": HTMLSSaqhanBreadCardElement;
        "s-saqhan-bread-crumbs": HTMLSSaqhanBreadCrumbsElement;
        "s-saqhan-card-author": HTMLSSaqhanCardAuthorElement;
        "s-saqhan-card-banner": HTMLSSaqhanCardBannerElement;
        "s-saqhan-chat-add-question": HTMLSSaqhanChatAddQuestionElement;
        "s-saqhan-chat-app": HTMLSSaqhanChatAppElement;
        "s-saqhan-chat-files": HTMLSSaqhanChatFilesElement;
        "s-saqhan-chat-files-wrapper": HTMLSSaqhanChatFilesWrapperElement;
        "s-saqhan-chat-form-search": HTMLSSaqhanChatFormSearchElement;
        "s-saqhan-chat-form-search-files": HTMLSSaqhanChatFormSearchFilesElement;
        "s-saqhan-chat-main-user": HTMLSSaqhanChatMainUserElement;
        "s-saqhan-chat-main-user-card": HTMLSSaqhanChatMainUserCardElement;
        "s-saqhan-chat-personal": HTMLSSaqhanChatPersonalElement;
        "s-saqhan-chat-user": HTMLSSaqhanChatUserElement;
        "s-saqhan-chat-user-card": HTMLSSaqhanChatUserCardElement;
        "s-saqhan-chat-users": HTMLSSaqhanChatUsersElement;
        "s-saqhan-chat-users-wrapper": HTMLSSaqhanChatUsersWrapperElement;
        "s-saqhan-chat-wrapper": HTMLSSaqhanChatWrapperElement;
        "s-saqhan-component": HTMLSSaqhanComponentElement;
        "s-saqhan-event-card": HTMLSSaqhanEventCardElement;
        "s-saqhan-events-blog": HTMLSSaqhanEventsBlogElement;
        "s-saqhan-first-slider": HTMLSSaqhanFirstSliderElement;
        "s-saqhan-header-app": HTMLSSaqhanHeaderAppElement;
        "s-saqhan-item-news": HTMLSSaqhanItemNewsElement;
        "s-saqhan-lenta-news-card": HTMLSSaqhanLentaNewsCardElement;
        "s-saqhan-line-book": HTMLSSaqhanLineBookElement;
        "s-saqhan-list-news": HTMLSSaqhanListNewsElement;
        "s-saqhan-main-news-card": HTMLSSaqhanMainNewsCardElement;
        "s-saqhan-new-blog": HTMLSSaqhanNewBlogElement;
        "s-saqhan-news-card": HTMLSSaqhanNewsCardElement;
        "s-saqhan-popular-card": HTMLSSaqhanPopularCardElement;
        "s-saqhan-popular-news": HTMLSSaqhanPopularNewsElement;
        "s-saqhan-quote-text": HTMLSSaqhanQuoteTextElement;
        "s-saqhan-second-page": HTMLSSaqhanSecondPageElement;
        "s-saqhan-subsc-banner": HTMLSSaqhanSubscBannerElement;
        "second-title-block": HTMLSecondTitleBlockElement;
    }
}
declare namespace LocalJSX {
    interface FooterFirstItem {
        "arr"?: any;
        "onClickOnMenu"?: (event: CustomEvent<any>) => void;
    }
    interface FooterWrapper {
        /**
          * массив 1 футера
         */
        "footer"?: FooterWrapperItem;
        /**
          * Клик на пункт меню
         */
        "onClickOnMenu"?: (event: CustomEvent<any>) => void;
    }
    interface MenuItem {
        "arr"?: any;
        "onClickOnMenu"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanAppFooter {
        /**
          * Инфо о компании в футере
         */
        "footerInfo"?: any;
        /**
          * массив меню для вывода
         */
        "footerItems"?: any;
        /**
          * клик по кнопке в футере
         */
        "onClickOnMenu"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanAuthorInfo {
        "author"?: any;
    }
    interface SSaqhanBlogCard {
        /**
          * Клик по category
         */
        "onClickOnCategoryNews"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
        /**
          * Массив с публикациями
         */
        "post"?: any;
    }
    interface SSaqhanBreadCard {
        "links"?: any;
    }
    interface SSaqhanBreadCrumbs {
        "links"?: any;
    }
    interface SSaqhanCardAuthor {
        "author"?: SSaqhanCardAuthorItem;
    }
    interface SSaqhanCardBanner {
        "bannerPost"?: SSaqhanCardBannerItem;
    }
    interface SSaqhanChatAddQuestion {
    }
    interface SSaqhanChatApp {
        "onClose"?: (event: CustomEvent<any>) => void;
        "onSelectFiles"?: (event: CustomEvent<any>) => void;
        "onSelectPersonal"?: (event: CustomEvent<any>) => void;
        "onSelectUsers"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanChatFiles {
    }
    interface SSaqhanChatFilesWrapper {
    }
    interface SSaqhanChatFormSearch {
        "onSelectFiles"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanChatFormSearchFiles {
        "onSelectUsers"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanChatMainUser {
        "mainUser"?: any;
    }
    interface SSaqhanChatMainUserCard {
        "main"?: any;
        "onSelectPersonal"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanChatPersonal {
        "onSelectUsers"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanChatUser {
        "messages"?: any;
    }
    interface SSaqhanChatUserCard {
        "onSelectPersonal"?: (event: CustomEvent<any>) => void;
        "user"?: any;
    }
    interface SSaqhanChatUsers {
        "mainUser"?: any;
        "messages"?: any;
    }
    interface SSaqhanChatUsersWrapper {
        "mainUser"?: any;
        "messages"?: any;
    }
    interface SSaqhanChatWrapper {
        "mainUser"?: any;
        "messages"?: any;
        "onClose"?: (event: CustomEvent<any>) => void;
        "onSelectFiles"?: (event: CustomEvent<any>) => void;
        "onSelectPersonal"?: (event: CustomEvent<any>) => void;
        "onSelectUsers"?: (event: CustomEvent<any>) => void;
        "showContent"?: string;
    }
    interface SSaqhanComponent {
    }
    interface SSaqhanEventCard {
        /**
          * Массив публикаций Ивентов
         */
        "event"?: any;
        /**
          * Клик по категории
         */
        "onClickOnCategoryNews"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanEventsBlog {
        /**
          * Массив с публикациями
         */
        "events"?: SSaqhanEventCardItem[];
        /**
          * Клик по категории
         */
        "onClickOnCategoryNews"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanFirstSlider {
        /**
          * массив новостей для вывода
         */
        "blogCarouselMock"?: SSaqhanFirstSliderItem[];
        /**
          * Фильтруем для ленты новостей
         */
        "onClickOnCategoryNews"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanHeaderApp {
        /**
          * ссылка на изображение логотипа
         */
        "logoUrl"?: logoUrl;
        /**
          * массив меню для вывода
         */
        "menu"?: SSaqhanHedearMenuItem[];
        /**
          * клик по конкретному меню
         */
        "onClickOnMenu"?: (event: CustomEvent<SSaqhanHedearMenuItem>) => void;
        /**
          * клик по кнопке подписаться
         */
        "onClickOnSubscribeButton"?: (event: CustomEvent<any>) => void;
        /**
          * клик по лого
         */
        "onClickToLogo"?: (event: CustomEvent<any>) => void;
        /**
          * текст вывода в кнопке подписаться
         */
        "subscribeText"?: string;
    }
    interface SSaqhanItemNews {
    }
    interface SSaqhanLentaNewsCard {
        /**
          * Массив с новостями для ленты
         */
        "lentaNews"?: any;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanLineBook {
        "banner"?: any;
    }
    interface SSaqhanListNews {
        "news"?: any;
    }
    interface SSaqhanMainNewsCard {
        /**
          * Массив с новостями
         */
        "mainNews"?: any;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanNewBlog {
        /**
          * Массив с публикациями
         */
        "blogPost"?: NewBlogItem[];
        /**
          * Клик по category
         */
        "onClickOnCategoryNews"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface SSaqhanNewsCard {
        "news"?: SSaqhanNewsCardItem;
    }
    interface SSaqhanPopularCard {
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
        /**
          * Массив с популярными элементами
         */
        "post"?: any;
    }
    interface SSaqhanPopularNews {
        /**
          * Данные для баннера
         */
        "bannerPopular"?: any;
        /**
          * Клик по новости
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
        /**
          * Массив публикаций
         */
        "popularNews"?: SSaqhanPopularCardItem[];
    }
    interface SSaqhanQuoteText {
        "quoteText"?: any;
    }
    interface SSaqhanSecondPage {
    }
    interface SSaqhanSubscBanner {
        /**
          * клик по кнопке подписаться
         */
        "onClickOnSubscribeButton"?: (event: CustomEvent<any>) => void;
        /**
          * Массив данных для черного баннера
         */
        "subscribeBlockText"?: any;
        /**
          * текст вывода в кнопке подписаться
         */
        "subscribeText"?: string;
    }
    interface SecondTitleBlock {
        "secondTitle"?: secondTitleBlockItem;
    }
    interface IntrinsicElements {
        "footer-first-item": FooterFirstItem;
        "footer-wrapper": FooterWrapper;
        "menu-item": MenuItem;
        "s-saqhan-app-footer": SSaqhanAppFooter;
        "s-saqhan-author-info": SSaqhanAuthorInfo;
        "s-saqhan-blog-card": SSaqhanBlogCard;
        "s-saqhan-bread-card": SSaqhanBreadCard;
        "s-saqhan-bread-crumbs": SSaqhanBreadCrumbs;
        "s-saqhan-card-author": SSaqhanCardAuthor;
        "s-saqhan-card-banner": SSaqhanCardBanner;
        "s-saqhan-chat-add-question": SSaqhanChatAddQuestion;
        "s-saqhan-chat-app": SSaqhanChatApp;
        "s-saqhan-chat-files": SSaqhanChatFiles;
        "s-saqhan-chat-files-wrapper": SSaqhanChatFilesWrapper;
        "s-saqhan-chat-form-search": SSaqhanChatFormSearch;
        "s-saqhan-chat-form-search-files": SSaqhanChatFormSearchFiles;
        "s-saqhan-chat-main-user": SSaqhanChatMainUser;
        "s-saqhan-chat-main-user-card": SSaqhanChatMainUserCard;
        "s-saqhan-chat-personal": SSaqhanChatPersonal;
        "s-saqhan-chat-user": SSaqhanChatUser;
        "s-saqhan-chat-user-card": SSaqhanChatUserCard;
        "s-saqhan-chat-users": SSaqhanChatUsers;
        "s-saqhan-chat-users-wrapper": SSaqhanChatUsersWrapper;
        "s-saqhan-chat-wrapper": SSaqhanChatWrapper;
        "s-saqhan-component": SSaqhanComponent;
        "s-saqhan-event-card": SSaqhanEventCard;
        "s-saqhan-events-blog": SSaqhanEventsBlog;
        "s-saqhan-first-slider": SSaqhanFirstSlider;
        "s-saqhan-header-app": SSaqhanHeaderApp;
        "s-saqhan-item-news": SSaqhanItemNews;
        "s-saqhan-lenta-news-card": SSaqhanLentaNewsCard;
        "s-saqhan-line-book": SSaqhanLineBook;
        "s-saqhan-list-news": SSaqhanListNews;
        "s-saqhan-main-news-card": SSaqhanMainNewsCard;
        "s-saqhan-new-blog": SSaqhanNewBlog;
        "s-saqhan-news-card": SSaqhanNewsCard;
        "s-saqhan-popular-card": SSaqhanPopularCard;
        "s-saqhan-popular-news": SSaqhanPopularNews;
        "s-saqhan-quote-text": SSaqhanQuoteText;
        "s-saqhan-second-page": SSaqhanSecondPage;
        "s-saqhan-subsc-banner": SSaqhanSubscBanner;
        "second-title-block": SecondTitleBlock;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "footer-first-item": LocalJSX.FooterFirstItem & JSXBase.HTMLAttributes<HTMLFooterFirstItemElement>;
            "footer-wrapper": LocalJSX.FooterWrapper & JSXBase.HTMLAttributes<HTMLFooterWrapperElement>;
            "menu-item": LocalJSX.MenuItem & JSXBase.HTMLAttributes<HTMLMenuItemElement>;
            "s-saqhan-app-footer": LocalJSX.SSaqhanAppFooter & JSXBase.HTMLAttributes<HTMLSSaqhanAppFooterElement>;
            "s-saqhan-author-info": LocalJSX.SSaqhanAuthorInfo & JSXBase.HTMLAttributes<HTMLSSaqhanAuthorInfoElement>;
            "s-saqhan-blog-card": LocalJSX.SSaqhanBlogCard & JSXBase.HTMLAttributes<HTMLSSaqhanBlogCardElement>;
            "s-saqhan-bread-card": LocalJSX.SSaqhanBreadCard & JSXBase.HTMLAttributes<HTMLSSaqhanBreadCardElement>;
            "s-saqhan-bread-crumbs": LocalJSX.SSaqhanBreadCrumbs & JSXBase.HTMLAttributes<HTMLSSaqhanBreadCrumbsElement>;
            "s-saqhan-card-author": LocalJSX.SSaqhanCardAuthor & JSXBase.HTMLAttributes<HTMLSSaqhanCardAuthorElement>;
            "s-saqhan-card-banner": LocalJSX.SSaqhanCardBanner & JSXBase.HTMLAttributes<HTMLSSaqhanCardBannerElement>;
            "s-saqhan-chat-add-question": LocalJSX.SSaqhanChatAddQuestion & JSXBase.HTMLAttributes<HTMLSSaqhanChatAddQuestionElement>;
            "s-saqhan-chat-app": LocalJSX.SSaqhanChatApp & JSXBase.HTMLAttributes<HTMLSSaqhanChatAppElement>;
            "s-saqhan-chat-files": LocalJSX.SSaqhanChatFiles & JSXBase.HTMLAttributes<HTMLSSaqhanChatFilesElement>;
            "s-saqhan-chat-files-wrapper": LocalJSX.SSaqhanChatFilesWrapper & JSXBase.HTMLAttributes<HTMLSSaqhanChatFilesWrapperElement>;
            "s-saqhan-chat-form-search": LocalJSX.SSaqhanChatFormSearch & JSXBase.HTMLAttributes<HTMLSSaqhanChatFormSearchElement>;
            "s-saqhan-chat-form-search-files": LocalJSX.SSaqhanChatFormSearchFiles & JSXBase.HTMLAttributes<HTMLSSaqhanChatFormSearchFilesElement>;
            "s-saqhan-chat-main-user": LocalJSX.SSaqhanChatMainUser & JSXBase.HTMLAttributes<HTMLSSaqhanChatMainUserElement>;
            "s-saqhan-chat-main-user-card": LocalJSX.SSaqhanChatMainUserCard & JSXBase.HTMLAttributes<HTMLSSaqhanChatMainUserCardElement>;
            "s-saqhan-chat-personal": LocalJSX.SSaqhanChatPersonal & JSXBase.HTMLAttributes<HTMLSSaqhanChatPersonalElement>;
            "s-saqhan-chat-user": LocalJSX.SSaqhanChatUser & JSXBase.HTMLAttributes<HTMLSSaqhanChatUserElement>;
            "s-saqhan-chat-user-card": LocalJSX.SSaqhanChatUserCard & JSXBase.HTMLAttributes<HTMLSSaqhanChatUserCardElement>;
            "s-saqhan-chat-users": LocalJSX.SSaqhanChatUsers & JSXBase.HTMLAttributes<HTMLSSaqhanChatUsersElement>;
            "s-saqhan-chat-users-wrapper": LocalJSX.SSaqhanChatUsersWrapper & JSXBase.HTMLAttributes<HTMLSSaqhanChatUsersWrapperElement>;
            "s-saqhan-chat-wrapper": LocalJSX.SSaqhanChatWrapper & JSXBase.HTMLAttributes<HTMLSSaqhanChatWrapperElement>;
            "s-saqhan-component": LocalJSX.SSaqhanComponent & JSXBase.HTMLAttributes<HTMLSSaqhanComponentElement>;
            "s-saqhan-event-card": LocalJSX.SSaqhanEventCard & JSXBase.HTMLAttributes<HTMLSSaqhanEventCardElement>;
            "s-saqhan-events-blog": LocalJSX.SSaqhanEventsBlog & JSXBase.HTMLAttributes<HTMLSSaqhanEventsBlogElement>;
            "s-saqhan-first-slider": LocalJSX.SSaqhanFirstSlider & JSXBase.HTMLAttributes<HTMLSSaqhanFirstSliderElement>;
            "s-saqhan-header-app": LocalJSX.SSaqhanHeaderApp & JSXBase.HTMLAttributes<HTMLSSaqhanHeaderAppElement>;
            "s-saqhan-item-news": LocalJSX.SSaqhanItemNews & JSXBase.HTMLAttributes<HTMLSSaqhanItemNewsElement>;
            "s-saqhan-lenta-news-card": LocalJSX.SSaqhanLentaNewsCard & JSXBase.HTMLAttributes<HTMLSSaqhanLentaNewsCardElement>;
            "s-saqhan-line-book": LocalJSX.SSaqhanLineBook & JSXBase.HTMLAttributes<HTMLSSaqhanLineBookElement>;
            "s-saqhan-list-news": LocalJSX.SSaqhanListNews & JSXBase.HTMLAttributes<HTMLSSaqhanListNewsElement>;
            "s-saqhan-main-news-card": LocalJSX.SSaqhanMainNewsCard & JSXBase.HTMLAttributes<HTMLSSaqhanMainNewsCardElement>;
            "s-saqhan-new-blog": LocalJSX.SSaqhanNewBlog & JSXBase.HTMLAttributes<HTMLSSaqhanNewBlogElement>;
            "s-saqhan-news-card": LocalJSX.SSaqhanNewsCard & JSXBase.HTMLAttributes<HTMLSSaqhanNewsCardElement>;
            "s-saqhan-popular-card": LocalJSX.SSaqhanPopularCard & JSXBase.HTMLAttributes<HTMLSSaqhanPopularCardElement>;
            "s-saqhan-popular-news": LocalJSX.SSaqhanPopularNews & JSXBase.HTMLAttributes<HTMLSSaqhanPopularNewsElement>;
            "s-saqhan-quote-text": LocalJSX.SSaqhanQuoteText & JSXBase.HTMLAttributes<HTMLSSaqhanQuoteTextElement>;
            "s-saqhan-second-page": LocalJSX.SSaqhanSecondPage & JSXBase.HTMLAttributes<HTMLSSaqhanSecondPageElement>;
            "s-saqhan-subsc-banner": LocalJSX.SSaqhanSubscBanner & JSXBase.HTMLAttributes<HTMLSSaqhanSubscBannerElement>;
            "second-title-block": LocalJSX.SecondTitleBlock & JSXBase.HTMLAttributes<HTMLSecondTitleBlockElement>;
        }
    }
}
