/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FirstSlider {
        "blogCarouselMock": any;
    }
    interface HeaderApp {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLFirstSliderElement extends Components.FirstSlider, HTMLStencilElement {
    }
    var HTMLFirstSliderElement: {
        prototype: HTMLFirstSliderElement;
        new (): HTMLFirstSliderElement;
    };
    interface HTMLHeaderAppElement extends Components.HeaderApp, HTMLStencilElement {
    }
    var HTMLHeaderAppElement: {
        prototype: HTMLHeaderAppElement;
        new (): HTMLHeaderAppElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "first-slider": HTMLFirstSliderElement;
        "header-app": HTMLHeaderAppElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FirstSlider {
        "blogCarouselMock"?: any;
    }
    interface HeaderApp {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "first-slider": FirstSlider;
        "header-app": HeaderApp;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "first-slider": LocalJSX.FirstSlider & JSXBase.HTMLAttributes<HTMLFirstSliderElement>;
            "header-app": LocalJSX.HeaderApp & JSXBase.HTMLAttributes<HTMLHeaderAppElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
